import google_base.bnf
import google_types.bnf

Grammar: RaisesGrammar

start: <raises-section>

<raises-section>
    ::= <raises> <colon> <newline> <items-exception> <newlines>

<items-exception>
    ::= <item-exception> <newline> <items-exception>
    | <item-exception>

<item-exception>
    ::= <head-exception> <line> <newline> <paragraph-indented-two>
    | <head-exception> <line>

<head-exception>
    ::= <indent> <exception> <colon>

<exception>
    ::= "TokenType\.WORD"
