import google_base.bnf


# Since we're not capturing commas, this assumes that a comma is
# present.  We'll probably want to add commas to the parsed symbols.
Grammar: TypesGrammar

start: <type-section>

<type-section>
    ::= <type-section-colon>
    | <type-section-parens>

<type-section-colon>
    ::= <type-words> <colon>

<type-section-parens>
    ::= <lparen> <type-words-colon> <rparen>

# The type words, but allowing colons.
<type-words-colon>
    ::= <type-word-colon> <type-words-colon>
    | <type-word-colon> <newline> <indents> <type-words-colon>
    | ε

<type-word-colon>
    ::= <ident>
    | "TokenType\.COLON"
    | "TokenType\.INDENT"

<type-words>
    ::= <type-word> <type-words>
    | <type-word> <newline> <indents> <type-words>
    | ε

<type-word>
    ::= <ident>
