import google_base.bnf
import google_types.bnf

from darglint.parse.identifiers import (
    ExceptionIdentifier,
    ExceptionItemIdentifier,
)

Grammar: RaisesGrammar

start: <raises-section>

<raises-section>
    ::= <raises> <colon> <newline> <items-exception> <newlines>

<items-exception>
    ::= <item-exception> <newline> <items-exception>
    | <item-exception>

<item-exception>
    ::= @ExceptionItemIdentifier
      <head-exception> <line> <newline> <paragraph-indented-two>
    | @ExceptionItemIdentifier
      <head-exception> <line>

<head-exception>
    ::= @ExceptionIdentifier <indent> <exception> <colon>

<exception>
    ::= "TokenType\.WORD"
