import terminals.bnf
import noqa_statement.bnf


<ident-list>
    ::= <ident>
    | <ident> <ident-list>

<block-indented>
    ::= <paragraph-indented> <split> <block-indented>
    | <paragraph-indented>

<paragraph-indented>
    ::= <indented> <line> <newline> <paragraph-indented>
    | <indented> <line>

<indented>
    ::= <indent> <indents>

<indents>
    ::= <indent> <indents>
    | ε

<split>
    ::= <newline> <newline> <newlines>

<newlines>
    ::= <newline> <newlines>
    | <newline>
    | ε

<line>
    ::= <word> <line>
    | <word> <noqa-maybe>
    | <noqa-statement>
