import numpy.bnf
import terminals.bnf

from darglint.parse.grammar import (
    BaseGrammar,
    P,
)
from darglint.parse.identifiers import (
    ExceptionItemIdentifier,
)


Grammar: RaisesGrammar

start: <raises-section>


<raises-section>
    ::= <raises-header> <newlines>
    | <raises-header> <newline> <raises-body> <newlines>

<raises-header>
    ::= <raises> <newline> <header>

<raises-body>
    ::= <raises-item> <newline> <raises-body>
    | <raises-item>

<raises-item>
    ::= @ExceptionItemIdentifier
        <ident> <newline>
        <block-indented>
    | <ident>
