import numpy.bnf
import terminals.bnf

from darglint.parse.grammar import (
    BaseGrammar,
    P,
)
from darglint.parse.identifiers import (
    ReturnTypeIdentifier,
)


Grammar: ReturnsGrammar

start: <returns-section>


<returns-section>
    ::= <returns-header> <newlines>
    | <returns-header> <newline> <returns-body> <newlines>

<returns-header>
    ::= <returns> <newline> <header>

# TODO: Change the yields body to match this.
<returns-body>
    ::= <block>
    | <returns-body-typed>

<returns-body-typed>
    ::= <returns-argument> <block-indented> <newline> <returns-body-typed>
    | <returns-argument> <block-indented> <newlines>

<returns-argument>
    ::= @ReturnTypeIdentifier <ident> <colon> <line> <newline>
    | @ReturnTypeIdentifier <ident> <newline>
