import sphinx_base.bnf

Grammar: ArgumentsGrammar

start: <arguments-section>

<arguments-section>
    ::= <ahead> <abody>

<ahead>
    ::= <colon> <arguments> <word> <colon> <newlines>
    | <colon> <arguments> <newline> <block-indented> <newlines>
    | <colon> <arguments> <argument-type-section> <word> <colon> <newlines>
    | <colon> <arguments> <argument-type-section> <newline> <block-indented> <newlines>

<argument-type-section>
    ::= <word>

<abody>
    ::= <line> <newlines>
    | <line> <newline> <block-indented> <newlines>
