import sphinx_base.bnf


Grammar: ReturnsGrammar

start: <returns-section>

<returns-section>
    ::= <rethead> <item-body> <newlines>
    | <rethead> <blanks> <item-body> <newlines>

<rethead>
    ::= <colon> <returns> <colon>
