import sphinx_base.bnf


Grammar: RaisesGrammar

start: <raises-section>

<raises-section>
    ::= <rhead> <item-body> <newlines>
    | <rhead> <blanks> <item-body> <newlines>

<rhead>
    ::= <colon> <raises> <word> <colon>
