import sphinx_base.bnf

Grammar: YieldsGrammar

start: <yields-section>

<yields-section>
    ::= <yhead> <item-body> <newlines>

<yield-type-section>
    ::= <word>

<yhead>
    ::= <colon> <yields> <colon>
    | <colon> <yields> <yield-type-section> <colon>
