import sphinx_base.bnf


Grammar: VariablesSectionGrammar

start: <variables-section>

<variables-section>
    ::= <vhead> <item-body>

<vhead>
    ::= <colon> <variables> <word> <colon>
    | <colon> <variables> <variable-type-section> <word> <colon>

<variable-type-section>
    ::= <word>
