import sphinx_base.bnf

from darglint.errors import (
    EmptyDescriptionError,
)

Grammar: VariableTypeGrammar

start: <variable-type-section>

<variable-type-section>
    ::= <varhead> <item-body> <newlines>
    | <varhead-no-follow> <newlines>

<varhead>
    ::= <colon> <variable-type> <word> <colon>

<varhead-no-follow>
    ::= @EmptyDescriptionError <colon> <variable-type> <word> <colon>
