import sphinx_base.bnf

from darglint.errors import (
    EmptyDescriptionError,
)

Grammar: ArgumentsGrammar

start: <arguments-section>

<arguments-section>
    ::= <ahead> <item-body>
    # This token gets elided up to the grammar,
    # So the children have to "know" than nothing comes after them.
    | <ahead-no-follow>

<ahead>
    ::= <colon> <arguments> <word> <colon> <newlines>
    | <colon> <arguments> <newline> <block-indented> <newlines>
    | <colon> <arguments> <argument-type-section> <word> <colon> <newlines>
    | <colon> <arguments> <argument-type-section> <newline> <block-indented> <newlines>

<ahead-no-follow>
    ::= @EmptyDescriptionError <colon> <arguments> <word> <colon> <newlines>
    | @EmptyDescriptionError <colon> <arguments> <newline> <block-indented> <newlines>
    | @EmptyDescriptionError <colon> <arguments> <argument-type-section> <word> <colon> <newlines>
    | @EmptyDescriptionError <colon> <arguments> <argument-type-section> <newline> <block-indented> <newlines>

<argument-type-section>
    ::= <word>
