import sphinx_base.bnf

Grammar: YieldsGrammar

start: <yields-section>

<yields-section>
    ::= <yhead> <ybody> <newlines>

<yield-type-section>
    ::= <word>

<yhead>
    ::= <colon> <yields> <colon>
    | <colon> <yields> <yield-type-section> <colon>

<ybody>
    ::= <line>
    | <line> <block-indented>
