import sphinx_base.bnf

Grammar: ArgumentsGrammar

start: <arguments-section>

<arguments-section>
    ::= <ahead> <item-body>

<ahead>
    ::= <colon> <arguments> <word> <colon> <newlines>
    | <colon> <arguments> <newline> <block-indented> <newlines>
    | <colon> <arguments> <argument-type-section> <word> <colon> <newlines>
    | <colon> <arguments> <argument-type-section> <newline> <block-indented> <newlines>

<argument-type-section>
    ::= <word>
