from darglint.token import (
    TokenType,
)

# TODO: Come up with common set of prefixes to handle possibly empty,
# indented, possibly-newline-terminated, strict, etc.

<word>
    ::= <colon>
    | <hash>
    | <indent>
    | <lparen>
    | <rparen>
    | <ident>

<word-colonless>
    ::= <ident>
    | <hash>
    | <indent>
    | <lparen>
    | <rparen>

<ident>
    ::= "TokenType\.WORD"
    | <raises>
    | <arguments>
    | <argument-type>
    | <raises>
    | <returns>
    | <return-type>
    | <yields>
    | <yield-type>
    | <variables>
    | <variable-type>
    | <noqa>

<arguments>
    ::= "TokenType\.ARGUMENTS"

<argument-type>
    ::= "TokenType\.ARGUMENT_TYPE"

<colon>
    ::= "TokenType\.COLON"

<hash>
    ::= "TokenType\.HASH"

<indent>
    ::= "TokenType\.INDENT"

<lparen>
    ::= "TokenType\.LPAREN"

<newline>
    ::= "TokenType\.NEWLINE"

<raises>
    ::= "TokenType\.RAISES"

<returns>
    ::= "TokenType\.RETURNS"

<return-type>
    ::= "TokenType\.RETURN_TYPE"

<rparen>
    ::= "TokenType\.RPAREN"

<yields>
    ::= "TokenType\.YIELDS"

<yield-type>
    ::= "TokenType\.YIELD_TYPE"

<variables>
    ::= "TokenType\.VARIABLES"

<variable-type>
    ::= "TokenType\.VARIABLE_TYPE"

<noqa>
    ::= "TokenType\.NOQA"
